# Generated by Django 4.2.1 on 2023-05-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_ofwhatuserlearnt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry_ofWhatUserLearnt',
            new_name='Entry',
        ),
    ]
